#!/bin/bash

# 🚀 QUICK START - UrbanGoal Notificaciones

echo "======================================"
echo "    UrbanGoal - Quick Start Setup"
echo "======================================"
echo ""

# Colores
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Paso 1: Configurar Email (Gmail SMTP)${NC}"
echo "----------------------------------------"
echo ""
echo "Necesitas:"
echo "1. Cuenta Google con 2FA habilitado"
echo "2. Una 'Contraseña de aplicación' (16 caracteres)"
echo ""
echo "Cómo obtenerla:"
echo "  1. Ve a https://myaccount.google.com/security"
echo "  2. Activa 'Verificación en 2 pasos'"
echo "  3. Ve a https://myaccount.google.com/apppasswords"
echo "  4. Selecciona 'Mail' + tu dispositivo"
echo "  5. Copia la contraseña generada"
echo ""
echo "Luego, edita UrbanGoal_BackEnd/.env:"
echo ""
echo -e "${YELLOW}EMAIL_USER=ncruzm2002@gmail.com${NC}"
echo -e "${YELLOW}EMAIL_PASSWORD=xxxx xxxx xxxx xxxx  # Tu contraseña de 16 caracteres${NC}"
echo -e "${YELLOW}ADMIN_EMAIL=ncruzm2002@gmail.com${NC}"
echo ""

echo -e "${BLUE}Paso 2: Configurar WhatsApp (Twilio - OPCIONAL)${NC}"
echo "----------------------------------------"
echo ""
echo "Necesitas:"
echo "1. Cuenta Twilio (obtiene $10 USD gratis)"
echo "2. Account SID"
echo "3. Auth Token"
echo ""
echo "Cómo obtenerlo:"
echo "  1. Ve a https://www.twilio.com"
echo "  2. Regístrate"
echo "  3. Dashboard → Account Info"
echo "  4. Copia Account SID y Auth Token"
echo "  5. Dashboard → Messaging → WhatsApp → Try it out"
echo ""
echo "Luego, edita UrbanGoal_BackEnd/.env:"
echo ""
echo -e "${YELLOW}TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx${NC}"
echo -e "${YELLOW}TWILIO_AUTH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx${NC}"
echo -e "${YELLOW}TWILIO_WHATSAPP_NUMBER=whatsapp:+14155238886${NC}"
echo ""

echo -e "${BLUE}Paso 3: Reiniciar Backend${NC}"
echo "----------------------------------------"
echo ""
echo "Ejecuta:"
echo -e "${YELLOW}docker-compose restart urbangoal-backend-1${NC}"
echo ""

echo -e "${BLUE}Paso 4: Probar${NC}"
echo "----------------------------------------"
echo ""
echo "1. Abre http://localhost:3000"
echo "2. Completa un pedido"
echo "3. Deberías recibir:"
echo "   ✉️ Email de confirmación"
echo "   📱 WhatsApp de confirmación (si configuraste Twilio)"
echo ""

echo -e "${GREEN}¡Listo! Las notificaciones están activadas 🎉${NC}"
echo ""
echo "======================================"
echo "          Información Importante"
echo "======================================"
echo ""
echo "📧 Sin Email: La app funciona, pero NO se envían notificaciones"
echo "📱 Sin WhatsApp: La app funciona, pero NO se envían mensajes"
echo ""
echo "🔒 Seguridad:"
echo "   - NUNCA hagas commit de .env a git"
echo "   - .env ya está en .gitignore"
echo "   - Usa .env.example como referencia"
echo ""
echo "📚 Documentación completa en:"
echo "   - NOTIFICACIONES_SETUP.md"
echo "   - CAMBIOS_REALIZADOS.md"
echo ""
echo "======================================"
